name: Publish release

on:
  release:
    types:
      - created

jobs:
  test-and-publish:
    runs-on: macos-latest
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: MAVEN_USERNAME # env variable for username in deploy
          server-password: MAVEN_CENTRAL_TOKEN # env variable for token in deploy
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }} # Value of the GPG private key to import
          gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase
      - name: Set release version
        run: ./mvnw versions:set -DnewVersion=${{ env.GITHUB_REF_SLUG }}
      - name: Unit test
        run: ./mvnw test
      - name: Build
        run: ./mvnw package
      - name: Publish
        run: ./mvnw deploy
        env:
          MAVEN_USERNAME: ${{ env.GITHUB_REPOSITORY_OWNER_PART_SLUG }}
          MAVEN_CENTRAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}